param(
    [Parameter(Position = 0)]
    [ValidateSet("doctor", "migrate", "build", "validate")]
    [string]$Command = "doctor",

    [string]$Name,
    [string]$From,
    [ValidateSet("codex", "claude-code", "antigravity")]
    [string]$Agent = "codex",
    [string[]]$Targets = @("codex", "claude-code", "antigravity"),
    [string]$Root = (Resolve-Path ".").Path
)

$ErrorActionPreference = "Stop"

function Join-Root {
    param([string[]]$Parts)
    return Join-Path -Path $Root -ChildPath ([System.IO.Path]::Combine($Parts))
}

function Ensure-Directory {
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Read-Text {
    param([string]$Path)
    return Get-Content -LiteralPath $Path -Raw -Encoding UTF8
}

function Write-Text {
    param([string]$Path, [string]$Content)
    $parent = Split-Path -Parent $Path
    if ($parent) { Ensure-Directory $parent }
    Set-Content -LiteralPath $Path -Value $Content -Encoding UTF8 -NoNewline
}

function Parse-SkillMarkdown {
    param([string]$Content, [string]$FallbackName)

    $name = $FallbackName
    $description = ""
    $body = $Content

    if ($Content -match '(?s)^---\s*\r?\n(.*?)\r?\n---\s*\r?\n?(.*)$') {
        $frontmatter = $Matches[1]
        $body = $Matches[2]
        foreach ($line in ($frontmatter -split "\r?\n")) {
            if ($line -match '^\s*name:\s*(.+?)\s*$') {
                $name = $Matches[1].Trim().Trim('"').Trim("'")
            }
            if ($line -match '^\s*description:\s*(.+?)\s*$') {
                $description = $Matches[1].Trim().Trim('"').Trim("'")
            }
        }
    }

    return [pscustomobject]@{
        Name = $name
        Description = $description
        Body = $body.Trim()
    }
}

function Read-SkillYaml {
    param([string]$SkillDir)

    $path = Join-Path $SkillDir "skill.yaml"
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing skill.yaml: $path"
    }

    $nameValue = ""
    $descriptionValue = ""
    $versionValue = "0.1.0"
    foreach ($line in (Get-Content -LiteralPath $path -Encoding UTF8)) {
        if ($line -match '^\s*name:\s*(.+?)\s*$') { $nameValue = $Matches[1].Trim().Trim('"').Trim("'") }
        if ($line -match '^\s*description:\s*(.+?)\s*$') { $descriptionValue = $Matches[1].Trim().Trim('"').Trim("'") }
        if ($line -match '^\s*version:\s*(.+?)\s*$') { $versionValue = $Matches[1].Trim().Trim('"').Trim("'") }
    }

    if (-not $nameValue) {
        throw "skill.yaml must include name: $path"
    }

    return [pscustomobject]@{
        Name = $nameValue
        Description = $descriptionValue
        Version = $versionValue
    }
}

function Get-GeneratedHeader {
    param([string]$SkillName, [string]$Target)

    return @"
<!--
Generated by SkillPort. Do not edit this file directly.

Source:
skills/$SkillName/

Target:
$Target

To improve this skill:
- Shared SOP: edit skills/$SkillName/sop.md
- Target-only behavior: edit skills/$SkillName/agents/$Target.md

Then run:
.\tools\skillport.ps1 build -Name $SkillName
.\tools\skillport.ps1 validate -Name $SkillName
-->

"@
}

function Copy-ResourceDirectories {
    param([string]$SourceSkillDir, [string]$TargetSkillDir)

    foreach ($dirName in @("references", "scripts", "assets", "agents")) {
        $source = Join-Path $SourceSkillDir $dirName
        if (Test-Path -LiteralPath $source) {
            $destination = Join-Path $TargetSkillDir $dirName
            if (Test-Path -LiteralPath $destination) {
                Remove-Item -LiteralPath $destination -Recurse -Force
            }
            Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
        }
    }
}

function Invoke-Doctor {
    Write-Host "SkillPort doctor"
    Write-Host "Root: $Root"
    Write-Host ("PowerShell: " + $PSVersionTable.PSVersion)
    Write-Host ("Git: " + ($(if (Get-Command git -ErrorAction SilentlyContinue) { "found" } else { "missing" })))
    foreach ($path in @(
        "$env:USERPROFILE\.codex\skills",
        "$env:USERPROFILE\.agents\skills",
        "$env:USERPROFILE\.claude\skills"
    )) {
        Write-Host ("Skills dir: {0} => {1}" -f $path, ($(if (Test-Path -LiteralPath $path) { "found" } else { "missing" })))
    }
}

function Invoke-Migrate {
    if (-not $From) { throw "migrate requires -From <skill-folder>" }
    if (-not (Test-Path -LiteralPath $From)) { throw "Source skill folder not found: $From" }

    $sourceSkill = Join-Path $From "SKILL.md"
    if (-not (Test-Path -LiteralPath $sourceSkill)) { throw "Source SKILL.md not found: $sourceSkill" }

    $fallbackName = Split-Path -Leaf $From
    $parsed = Parse-SkillMarkdown -Content (Read-Text $sourceSkill) -FallbackName $fallbackName
    $skillName = if ($Name) { $Name } else { $parsed.Name }

    $skillDir = Join-Root @("skills", $skillName)
    $adapterDir = Join-Path $skillDir "agents"
    Ensure-Directory $adapterDir

    $description = if ($parsed.Description) { $parsed.Description } else { "Imported portable skill." }

    Write-Text -Path (Join-Path $skillDir "skill.yaml") -Content @"
name: $skillName
description: $description
version: 0.1.0
targets:
  - codex
  - claude-code
  - antigravity
"@

    Write-Text -Path (Join-Path $skillDir "sop.md") -Content @"
# Shared SOP

> Imported by SkillPort from $From.
> This first migration is intentionally no-loss. Move target-only details into agent notes during later refactors.

$($parsed.Body)
"@

    foreach ($target in $Targets) {
        $adapterPath = Join-Path $adapterDir "$target.md"
        if ($target -eq $Agent) {
            $adapterContent = @"
# $target Agent Notes

These agent notes were initialized from the source skill imported from:

    $From

## Maintenance

- Keep shared workflow changes in skills/$skillName/sop.md.
- Keep $target-only runtime behavior in these agent notes.
- Rebuild generated packages after every change.

## Target Notes

- Source agent during migration: $Agent.
- Review `sop.md` and move platform-specific tool names, hook files, or install paths into these agent notes when they are not shared.
"@
        }
        else {
            $adapterContent = @"
# $target Agent Notes

These agent notes are a migration stub.

## Maintenance

- Keep shared workflow changes in skills/$skillName/sop.md.
- Add only $target-specific tool names, runtime rules, loading behavior, and installation notes here.
- Rebuild generated packages after every change.

## Target Notes

- Review the shared SOP before using this generated package in $target.
- Add explicit $target runtime guidance before publishing this package broadly.
"@
        }
        Write-Text -Path $adapterPath -Content $adapterContent
    }

    foreach ($dirName in @("references", "scripts", "assets", "agents")) {
        $source = Join-Path $From $dirName
        if (Test-Path -LiteralPath $source) {
            $destination = Join-Path $skillDir $dirName
            if (Test-Path -LiteralPath $destination) {
                Remove-Item -LiteralPath $destination -Recurse -Force
            }
            Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
        }
    }

    Write-Text -Path (Join-Path $skillDir "migration.md") -Content @"
# Migration

Source agent: $Agent
Source path: $From
Migrated at: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz")

## Original files

- SKILL.md

## Decisions

- Preserved the imported body in sop.md for a no-loss first migration.
- Created one agent notes file per target agent.
- Copied resource directories when present.
- Generated runtime packages should be rebuilt from this source, not edited directly.
"@

    Write-Host "Migrated skill: $skillName"
    Write-Host "Source: $skillDir"
}

function Invoke-Build {
    if (-not $Name) { throw "build requires -Name <skill-name>" }

    $skillDir = Join-Root @("skills", $Name)
    if (-not (Test-Path -LiteralPath $skillDir)) { throw "Skill source not found: $skillDir" }

    $meta = Read-SkillYaml -SkillDir $skillDir
    $sopPath = Join-Path $skillDir "sop.md"
    if (-not (Test-Path -LiteralPath $sopPath)) { throw "Missing sop.md: $sopPath" }
    $sop = Read-Text $sopPath

    foreach ($target in $Targets) {
        $adapterPath = Join-Path (Join-Path $skillDir "agents") "$target.md"
        if (-not (Test-Path -LiteralPath $adapterPath)) { throw "Missing agent notes: $adapterPath" }

        $targetDir = Join-Root @("dist", $target, $meta.Name)
        Ensure-Directory $targetDir

        $frontmatter = @"
---
name: $($meta.Name)
description: $($meta.Description)
---

"@

        $content = (Get-GeneratedHeader -SkillName $meta.Name -Target $target) +
            $frontmatter +
            (Read-Text $adapterPath).Trim() +
            "`r`n`r`n---`r`n`r`n" +
            $sop.Trim() +
            "`r`n"

        Write-Text -Path (Join-Path $targetDir "SKILL.md") -Content $content
        Copy-ResourceDirectories -SourceSkillDir $skillDir -TargetSkillDir $targetDir
        Write-Host "Generated: $targetDir"
    }
}

function Invoke-Validate {
    if (-not $Name) { throw "validate requires -Name <skill-name>" }

    $errors = New-Object System.Collections.Generic.List[string]
    $warnings = New-Object System.Collections.Generic.List[string]
    $sourceDir = Join-Root @("skills", $Name)

    if (-not (Test-Path -LiteralPath $sourceDir)) {
        $errors.Add("Missing source skill: $sourceDir")
    }
    else {
        $skillYaml = Join-Path $sourceDir "skill.yaml"
        $sop = Join-Path $sourceDir "sop.md"
        $maintenance = Join-Path $sourceDir "maintenance.md"
        $agents = Join-Path $sourceDir "agents"

        if (-not (Test-Path -LiteralPath $skillYaml)) { $errors.Add("Missing skill.yaml: $skillYaml") }
        if (-not (Test-Path -LiteralPath $sop)) { $errors.Add("Missing sop.md: $sop") }
        if (-not (Test-Path -LiteralPath $maintenance)) { $warnings.Add("Missing maintenance.md: $maintenance") }
        if (-not (Test-Path -LiteralPath $agents)) { $warnings.Add("Missing agents notes directory: $agents") }

        if (Test-Path -LiteralPath $skillYaml) {
            $meta = Read-SkillYaml -SkillDir $sourceDir
            if ($meta.Name -ne $Name) { $errors.Add("skill.yaml name '$($meta.Name)' does not match -Name '$Name'") }
            if (-not $meta.Description) { $warnings.Add("skill.yaml has an empty description: $skillYaml") }
        }

        if (Test-Path -LiteralPath $sop) {
            $sopText = Read-Text $sop
            if ($sopText.Trim().Length -lt 40) { $warnings.Add("sop.md is very short: $sop") }
        }
    }

    if ($errors.Count -gt 0) {
        Write-Host "Validation failed:"
        foreach ($errorItem in $errors) {
            Write-Host "- $errorItem"
        }
        exit 1
    }

    Write-Host "Validation passed for source skill: $Name"
    if ($warnings.Count -gt 0) {
        Write-Host "Warnings:"
        foreach ($warningItem in $warnings) {
            Write-Host "- $warningItem"
        }
    }
}

switch ($Command) {
    "doctor" { Invoke-Doctor }
    "migrate" { Invoke-Migrate }
    "build" { Invoke-Build }
    "validate" { Invoke-Validate }
}
